import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { HUB_KEYWORD_SHARDS } from '../../src/core/patriot/data/hubKeywordShards.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const OUTPUT_FILE = path.join(__dirname, '..', '..', 'src', 'core', 'patriot', 'data', 'intentSignals.js');

function generate() {
  const intents = [];
  const timestamp = new Date().toISOString();

  for (const [code, shard] of Object.entries(HUB_KEYWORD_SHARDS)) {
    const allKeywords = [
      ...(shard.logisticsKeywords || []),
      ...(shard.capabilityKeywords || []),
      ...(shard.routeLinkedKeywords || [])
    ];

    for (const kw of allKeywords) {
      intents.push({
        keyword: kw,
        airportCode: code,
        operatorId: "patriot-pipeline",
        sourceUrl: "internal://hub-keyword-shards",
        pageTitle: null,
        metaDescription: null,
        brandsMentioned: [],
        modelsMentioned: [],
        categoriesMentioned: [],
        priceSignals: [],
        lastSeenAt: timestamp,
        frequency: 1
      });
    }
  }

  const serialized = JSON.stringify(intents, null, 2);

  const output = `// Intent signals data — auto-generated by scripts/seo/generateIntentSignals.mjs
// Last updated: ${timestamp}
// Source: hubKeywordShards.js, ${intents.length} signals

const INTENT_SIGNALS = ${serialized};

export { INTENT_SIGNALS };
`;

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`[GenerateIntentSignals] ✅ Flattened ${intents.length} intents from ${Object.keys(HUB_KEYWORD_SHARDS).length} shards → intentSignals.js`);
}

generate();
