const fs = require("fs");
const path = require("path");

const MASTER_FILE = path.join(__dirname, "..", "data", "intent_harvests", "master_intents.json");
const OUTPUT_FILE = path.join(
  __dirname, "..", "frontend", "rideratlas", "src",
  "core", "patriot", "data", "intentSignals.js"
);

function transformIntents() {
  if (!fs.existsSync(MASTER_FILE)) {
    console.log("[TransformIntents] No master_intents.json found — writing empty placeholder");
    const empty = `// Intent signals data — populated by \`npm run harvest:intent:pipeline\`.\n// Empty array = no intent signals harvested yet (overlay builder gracefully skips).\n\nconst INTENT_SIGNALS = [];\n\nexport { INTENT_SIGNALS };\n`;
    fs.writeFileSync(OUTPUT_FILE, empty);
    return;
  }

  const master = JSON.parse(fs.readFileSync(MASTER_FILE, "utf-8"));
  const intents = master.intents || [];

  console.log(`[TransformIntents] ${intents.length} intents from master_intents.json`);

  const serialized = JSON.stringify(intents, null, 2);

  const output = `// Intent signals data — auto-generated by scripts/transformIntents.js
// Last updated: ${master.lastUpdated || new Date().toISOString()}
// Source: ${master.stats?.sourceFiles || 0} harvest files, ${intents.length} signals

const INTENT_SIGNALS = ${serialized};

export { INTENT_SIGNALS };
`;

  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`[TransformIntents] ✅ ${intents.length} intents → intentSignals.js`);
}

transformIntents();
